GateController/GateController.API/Models/DTOs/Input/NewMember.cs
namespace GateController.API.Models.DTOs.Input
{
    public class NewMember
    {
        public string CardId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
    }
}

GateController/GateController.API/Models/DTOs/Input/RFIDData.cs
using GateController.API.Middlewares.WS;
using System.Text.Json.Serialization;

namespace GateController.API.Models.DTOs.Input
{
    public class RFIDData:BaseMessage
    {
        [JsonPropertyName("cId")]
        public string CardId { get; set; }
    }
}

GateController/GateController.API/Models/DTOs/Output/LoginResponse.cs
using System.Text.Json.Serialization;
using static GateController.API.Middlewares.WS.BaseMessage;

namespace GateController.API.Models.DTOs.Output
{
    public class LoginResponse
    {
        [JsonPropertyName("mT")]
        public MessageType Messagetype { get; set; } = MessageType.LoginMessage;
        public int MyProperty { get; set; }
    }
}

GateController/GateController.API/ViewModels/LogModel.cs
namespace GateController.API.ViewModels
{
    public class LogModel
    {
        public long CardId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime LoginDate { get; set; }
    }
}

GateController/GateController.API/ViewModels/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace GateController.API.ViewModels
{
    public class LoginModel
    {
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

GateController/GateController.API/ViewModels/OfficeMemberModel.cs
namespace GateController.API.ViewModels
{
    public class OfficeMemberModel
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
    }
}

GateController/GateController.API/Controllers/AdminController.cs
using GateController.API.Models.DTOs.Input;
using GateController.API.ViewModels;
using GateController.Repository;
using GateController.Repository.Entities;
using Microsoft.AspNetCore.Mvc;

namespace GateController.API.Controllers
{
    public class AdminController : Controller
    {
        private readonly SystemCardsRepository _systemCardsRepository;
        public AdminController(SystemCardsRepository systemCardRepo)
        {
            _systemCardsRepository = systemCardRepo;    
        }

        [HttpGet]
        [Route("/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("/LoginClick")]
        public IActionResult LoginClick(LoginModel loginModel)
        {
            if (loginModel.UserName== "admin" && loginModel.Password=="1234")
            {
                return RedirectToAction("Log", "Log");
            }

            return RedirectToAction("Login","Admin");   
        }

        [HttpGet]
        [Route("/NewMember")]
        public IActionResult NewMember()
        {
            return View();
        }

        [HttpPost]
        [Route("/NewMemberSave")]
        public async Task<IActionResult> NewMemberSave(NewMember member)
        {
            var card = new SystemCard { CardHex = member.CardId, OfficeMember = new OfficeMember { Name = member.Name, Surname = member.Surname, Phone = member.Phone } };
            await _systemCardsRepository.NewCard(card);
            return Content("Başarılı");
        }
    }
}

GateController/GateController.API/Controllers/LogController.cs
using GateController.API.ViewModels;
using GateController.Repository;
using Microsoft.AspNetCore.Mvc;

namespace GateController.API.Controllers
{
    public class LogController : Controller
    {
        private readonly GateLogRepository _gateLogRepository;
        public LogController(GateLogRepository gateLogRepo)
        {
            _gateLogRepository = gateLogRepo;
        }

        [HttpGet]
        [Route("/Log")]
        public async Task<IActionResult> Log()
        {
            var logList = await _gateLogRepository.GetAll();
            var modelList = new List<LogModel>();
            foreach (var item in logList)
            {
                modelList.Add(new LogModel
                {
                    CardId = item.Id,
                    LoginDate = item.LoginDate,
                    Name = item.OfficeMember.Name,
                    Surname = item.OfficeMember.Surname,
                });
            }

            return View(modelList);
        }
        
    }
}

GateController/GateController.API/Controllers/OfficeMemberController.cs
using GateController.API.ViewModels;
using GateController.Repository;
using Microsoft.AspNetCore.Mvc;

namespace GateController.API.Controllers
{
    public class OfficeMemberController : Controller
    {
        private readonly OfficeMemberRepository _officeMemberRepository;
        public OfficeMemberController(OfficeMemberRepository officeMemberRepo)
        {
            _officeMemberRepository = officeMemberRepo;
        }

        [HttpGet]
        [Route("/OfficeMember")]
        public async Task<IActionResult> OfficeMember()
        {
            var model = new List<OfficeMemberModel>();
            var list = await _officeMemberRepository.GetAll();

            list.ForEach(x => model.Add(new OfficeMemberModel
            {
                Name = x.Name,
                Phone = x.Phone,
                Surname = x.Surname
            }));

            return View(model);
        }
    }
}

GateController/GateController.API/Controllers/RemoteGateController.cs
using GateController.API.Middlewares.WebsocketMiddleware;
using GateController.API.Middlewares.WS;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;

namespace GateController.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RemoteGateController : ControllerBase
    {
        private readonly WSServerConnectionManager _conectionManager;
        public RemoteGateController(WSServerConnectionManager connectionManager)
        {
            _conectionManager = connectionManager;
        }
        [HttpPost("[action]")]
        public async Task<IActionResult> SendRegisterSignal()
        {
            var deviceConnection = _conectionManager.WSConnections.FirstOrDefault(x => x.Value.ClientType == Middlewares.WS.ClientType.Device);
            if (deviceConnection.Key == null)
                return BadRequest();

            await SendMessageAsync(deviceConnection.Value.Socket, JsonSerializer.Serialize(new { mT = BaseMessage.MessageType.RegisterMessage, d = string.Empty }));
            return Ok();
        }

        [HttpPost("[action]")]
        public IActionResult RemoveAllConnection()
        {
            _conectionManager.WSConnections.Clear();
            return Ok();
        }

        [HttpPost("[action]")]
        public IActionResult GetAllConnection() => Ok(_conectionManager.WSConnections);
        

        [NonAction]
        private async Task SendMessageAsync(WebSocket socket, string message)
        {
            await socket.SendAsync(Encoding.UTF8.GetBytes(message), WebSocketMessageType.Text, true, new CancellationTokenSource(1000 * 10).Token);
        }
    }
}

GateController/GateController.API/Views/Admin/Login.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>SGS</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sign In Start -->
        <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-light rounded p-4 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a href="komisyon.html" class="">
                                <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i></h3>
                            </a>
                            <h3>SSGM</h3>
                        </div>
                         <form method="post" action="/LoginClick">
                        <div class="form-floating mb-4">
                            <input type="text" class="form-control" id="UserName" name="UserName">
                            <label for="floatingPassword">Kullanıcı</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="Password" name="Password">
                            <label for="floatingPassword">Şifre</label>
                        </div>
                        <!-- <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                            <a href="">Forgot Password</a>
                        </div> -->
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Bağlan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

GateController/GateController.API/Views/Admin/NewMember.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>SSGM</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="komisyon.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>SSGM</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">

                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>

                </div>
                <div class="navbar-nav w-100">
                    <a href="/log" class="nav-item nav-link"><i class="fa fa-laptop me-2"></i>Logs</a>
                    <a href="/NewMember" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Kayıt</a>
                    <a href="/OfficeMember" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Kullanıcılar</a>

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="komisyon.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">

                            <span class="d-none d-lg-inline-flex">Admin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/Login" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <!-- Form Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">

                            <form method="post" action="/NewMemberSave">
                                <div class="mb-3">
                                    <label for="exampleInputEmail1" class="form-label">Kart ID</label>
                                    <input disabled="disabled" type="text" class="form-control" id="CardId" name="CardId">

                                </div>
                                <div class="mb-3">
                                    <button type="button" id="getId">Kart Okuma Modunu Başlat</button>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleInputPassword1" class="form-label">Ad</label>
                                    <input disabled="disabled" type="text" class="form-control" id="Name" name="Name">
                                </div>
                                <div class="mb-3">
                                    <label for="exampleInputPassword1" class="form-label">Soyad</label>
                                    <input disabled="disabled" type="text" class="form-control" id="Surname" name="Surname">
                                </div>
                                <div class="mb-3">
                                    <label for="exampleInputPassword1" class="form-label">Telefon</label>
                                    <input disabled="disabled" type="tel" class="form-control" id="Phone" name="Phone">
                                </div>

                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!-- Form End -->
            <!-- Content End -->
            <!-- Back to Top -->
            <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/chart/chart.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/tempusdominus/js/moment.min.js"></script>
        <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>
        <script>
                var socket = new WebSocket("ws://socket.metincembayraktar.com/ws?ct=2&cId=527023bd-f5ddsad");

                socket.onopen = function (e) {
                    console.log("Başarılı");
                };

                socket.onmessage = function (event) {
                    var jsonData = JSON.parse(event.data);
                    if (jsonData.MessageType == 16)
                    {
                        $("#kartid").val(jsonData.CardHex);
                        $("#nameSurname").removeAttr("disabled");
                        $("#tel").removeAttr("disabled");
                        console.log(jsonData.CardHex);
                    }
                };

                socket.onclose = function (event) {
                    if (event.wasClean) {
                        alert(`[close] Connection closed cleanly, code=${event.code} reason=${event.reason}`);
                    } else {
                        // e.g. server process killed or network down
                        // event.code is usually 1006 in this case
                        alert('[close] Connection died');
                    }
                };

                socket.onerror = function (error) {
                    alert(`[error]`);
                };
            $(function() {
                $("#getId").on("click", function() {
                    $.ajax({
                            url: '@Url.Action("SendRegisterSignal", "RemoteGate")',
                            method: "POST",
                            success: function(data)
                            {
                                console.log("Kart okunuyor. Lütfen bekleyin.");
                            },
                            error: function (request, status, error){
                                alert("Kart okuyucu sisteme bağlı değil.");
                            }
                    })
                });
            });
        </script>
</body>

</html>